<a href="https://colab.research.google.com/github/Aayush360/Natural_langauge_processing/blob/main/Sentiment_Analysis_using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.youtube.com/watch?v=CcGf_Uo7NMw&list=PL1w8k37X_6L_s4ncq-swTBvKDWnRSrinI&index=13

link to video tutorial: 

In [1]:
# one-hot representation

In [3]:
from keras.preprocessing.text import one_hot

# define documents

docs =['glass of orange juice',
       'bottle of mango juice',
       'glass of mango shake',
       'drink bottle of banana shake',
       'I want a glass of cold water',
       'The king and the queen',
       'man and women']


vocab_size = 10000
encoded_docs = [one_hot(d,vocab_size) for d in docs]
print(encoded_docs)

[[8840, 7764, 3228, 4611], [3464, 7764, 7858, 4611], [8840, 7764, 7858, 7187], [3145, 3464, 7764, 6970, 7187], [2476, 172, 2511, 8840, 7764, 1825, 9530], [259, 1835, 6154, 259, 7153], [5710, 6154, 4803]]


In [4]:
## Word-Embeddings

In [9]:
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM

import numpy as np


embedding_length = 5
max_doc_length = 10

encoded_docs = pad_sequences(encoded_docs,maxlen=max_doc_length,truncating='post',padding='post')
print(encoded_docs)

# each document will now have length of 10
# and embedding vector size is 5, and each word will be denoted by vector of size of 5

[[8840 7764 3228 4611    0    0    0    0    0    0]
 [3464 7764 7858 4611    0    0    0    0    0    0]
 [8840 7764 7858 7187    0    0    0    0    0    0]
 [3145 3464 7764 6970 7187    0    0    0    0    0]
 [2476  172 2511 8840 7764 1825 9530    0    0    0]
 [ 259 1835 6154  259 7153    0    0    0    0    0]
 [5710 6154 4803    0    0    0    0    0    0    0]]


In [ ]:
model = Sequential()
model.add(Embedding(vocab_size,embedding_length, input_length=max_doc_length))

model.add(LSTM(units=64)) # output of LSTM is 7x64 , 7 doc each represeted by vector of length 64

model.compile('rmsprop','mse')

model.summary()

output = model.predict(encoded_docs)
print(output.shape)
print(output) # 7 docs, each sentence/doc has 10 words, and each word represented by vecotor of length 5 